name: Static Code Analysts Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  tsc:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: npm i --legacy-peer-deps
      - name: TypeScript tsc
        run: ./node_modules/.bin/tsc --project tsconfig.json --noEmit

  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: npm i --legacy-peer-deps
      - name: Lint TypeScript
        run: npm run eslint

  stylelint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: npm i --legacy-peer-deps
      - name: Lint TypeScript
        run: npm run stylelint

  axe:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: npm i --legacy-peer-deps
      - name: Update Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable
      - name: Run axe
        run: npm run ci
